### ISSUE TITLE
Bidirectional communication with missive and net

### ISSUE THREAD

**Issue by agauniyal** [StarryInternet/missive#12]
I'm using missive to perform bi-directional communication b/w tcp sockets and would like to have this clarified that does order of `pipe()` call matter here -

server.js
```js
const net = require('net');
const missive = require('missive');

const server = net.createServer();

server.listen(1337);

server.on('connection', socket => {
	const encode = missive.encode();
	encode
		.pipe(socket)
		.pipe(missive.parse())
		.on('message', obj => {
			console.log(obj);
			encode.write({ hello: 'world' });
		});
	encode.write({ start: 1 });
});
```

client.js
```js
const net = require('net');
const missive = require('missive');
const encode = missive.encode();

const socket = net.createConnection({ port: 1337 });

encode
	.pipe(socket)
	.pipe(missive.parse())
	.on('message', obj => {
		console.log(obj);
		encode.write({ bye: 'world' });
	});
```

I'm talking about `encode.pipe(socket).pipe(missive.parse())` sequence. Does it matter if I put `missive.parse()` before `socket` in pipe calls? Also thanks for creating this module and saving my time, I would've to write this from scratch instead 😄

**Comment by spmurrayzzz** [comment]
Assuming you want the `data` events for `socket` to be piped to a missive parser, then what you've written will do just that. `pipe()` always returns a reference to the destination stream argument that you've provided. It helps to visualize it without chaining:

```js
// with chaining
encode.pipe( socket ).pipe( missive.parse() )

// without chaining
const socketRef   = encode.pipe( socket );
const parser      = socketRef.pipe( missive.parse() );

socketRef === socket; // `true`

parser.on( 'message', console.log );

encode.write({ myMessage: 'hello' });
```

So order does matter, but it depends on the behavior you're looking for in your application.

Does that answer your question?

**Comment by agauniyal** [comment]
What would happen if instead of `encode.pipe( socket ).pipe( missive.parse() )` I do `encode.pipe( missive.parse() ).pipe( socket )` ?

**Comment by spmurrayzzz** [comment]
Both of those lines do completely different things. 

If we remove chaining it becomes more clear:
```js
// Example 1: encode.pipe( socket ).pipe( missive.parse() )
const socketRef = encode.pipe( socket );
const parser    = socketRef.pipe( missive.parse() );

// Example 2: encode.pipe( missive.parse() ).pipe( socket )
const parser      = encode.pipe( missive.parse() );
const socketRef   = parser.pipe( socket );
```

Example 1 pipes data to a socket and then pipes the socket's `data` events to a missive parser stream.
Example 2 pipes data to a missive parser and then pipes the parser `data` events to the socket

Again these are entirely different things. I suggest you take a look at the Node.js docs for the `stream` module, might help you dig into how this works a little more: https://nodejs.org/dist/latest-v8.x/docs/api/stream.html 

Gonna close this issue because its not related directly to `missive`, but rather to Node streams in general.

**Comment by kevincennis** [comment]
Just to expand a bit on what @spmurrayzzz said:

- An `encode()` stream should always be piped to your TCP socket.
- Your TCP socket should then be piped to a `parse()` stream.

If you do `encode.pipe( missive.parse() ).pipe( socket )`, what actually happens is:

1. You're writing JavaScript Objects to `encode()`
2. `encode()` transforms those into framed binary data
3. `parse()` transforms them _back_ into JavaScript objects
4. Those JavaScript objects get sent to your TCP socket.

What you want with missive is to always _send_ encoded data to TCP, and always _read_ encoded data from TCP.

That's why you run it through `encode()` on the way in and through `parse()` on the way out.
